### PR TITLE
Creates color table for the design system

### PR DESCRIPTION
**Pull request by fjp2cornell**

### CODE REVIEW

**Comment by a-fro** [comment]
Hey John. Remember the idea that when you repeat something over and over in code, it's a "code smell"? It usually indicates that you need to refactor. Please take a look at one of many articles such as https://robots.thoughtbot.com/removing-sass-duplication on using Sass to "dry" (don't repeat yourself) up code. Let me know if you have questions.

**Comment by a-fro** [comment]
Thanks John. I'm not trying to be difficult, but do you notice anything else that isn't "dry" in your code? See how your $brand-colors array all repeat the same key/values? Is that necessary? 

Also, what are your thoughts about calculating the font color based on brightness of the background? Something like https://gist.github.com/jlong/f06f5843104ee10006fe?

**Comment by daviddemello** [comment]
John, I took a quick look at the code and at the links that Aaron supplied and I think that he's pointing out that you could replace:

$brand-colors: (cornell-red: $cornell-red, darker-red: $darker-red, bg-body: $bg-body, gray-bg: $gray-bg, nav-dark: $nav-dark, ochre-tan: $ochre-tan, ochre-green: $ochre-green, promo-color: $promo-color, event-color: $event-color, spotlight-color: $spotlight-color, student-portrait-color: $student-portrait-color, news-color: $news-color, video-color: $video-color, gray-dark: $gray-dark, gray-medium: $gray-medium, gray-light: $gray-light);

table.colors {
  @each $design-color, $hex-code in $brand-colors {
    .#{$design-color} {
      td {
        background: $hex-code;
        color: white;
        @if $design-color == 'bg-body' or $design-color == 'gray-dark' or $design-color == 'gray-medium' or $design-color == 'gray-light' or $design-color == 'gray-bg' {
          color: black;
        }
      }
    }
  }
  td {
    border-right: none;
    padding-left: 2em;
    height: 60px;
  }
}


with this:

$brand-colors: cornell-red, darker-red, bg-body, gray-bg, nav-dark, ochre-tan, ochre-green, promo-color, event-color, spotlight-color, student-portrait-color, news-color, video-color, gray-dark, $gray-medium, gray-light;

table.colors {
  @each $design-color in $brand-colors {
    .#{$design-color} {
      td {
        background: $design-color;
        color: white;
        @if $design-color == 'bg-body' or $design-color == 'gray-dark' or $design-color == 'gray-medium' or $design-color == 'gray-light' or $design-color == 'gray-bg' {
          color: black;
        }
      }
    }
  }
  td {
    border-right: none;
    padding-left: 2em;
    height: 60px;
  }
}

**Comment by daviddemello** [comment]
John, what are your thoughts on calculating color based on background-color to optimize contrast and legibility? I think it's worth a try to drop in the solution that Aaron references to see if the result is actually better than being forced to choose between black or white.

**Comment by a-fro** [comment]
Thanks @daviddemello. Your code is nearly correct. However, the list of $brand-colors should actually be the variables, which will then lead to a modification of the code in the @if directive (if it stays). See the codepen at http://codepen.io/anon/pen/OMramL as an example, and feel free to play with that to see the difference in the output (you just click the "view compiled" button).

**Comment by daviddemello** [comment]
Thanks. I get it. I was actually working from an example with cities in https://robots.thoughtbot.com/removing-sass-duplication where he uses a list of values rather than variables. 

So, in your codepen, deleting the variable declarations and substituting `$colors: $red, $blue;` with `$colors: red, blue;` also compiles as expected/desired.

The one stray variable `$gray-medium` in my list above was actually a typo. I see your point since, in our case, those variables are already defined elsewhere so we should just use them.

**Comment by fjp2cornell** [comment]
The code started with the example that David supplied where the list items were not mapped to a value. When I compiled the the css and inspected the element in the browser, the color was showing up as the variable name, cornell-red, darker-red, etc.  I tried adding the # symbol but sass balked at it even when I tried to escape it with an additional #.

Mapping the value fixed the problem with the browser.  I was not aware that I could put the variables in the list without mapping them to a value.

Thank you for the code pen solution, that was helpful.

**Comment by fjp2cornell** [comment]
Aaron the suggestion and link you provided about calculating the font color based on the background color is an idea I mentioned a little while ago when we first started talking about our primary and secondary colors. I don't know if this is the same code.

I would be in favor of exploring that further but perhaps at a later date as I would like to focus on finishing work for the experience reports.

**Comment by daviddemello** [comment]
As it turns out, the redundancy may be necessary. Take another look at the codepen and notice that $blue = cyan, but when the Sass compiles, the result is: 
body.cyan {background-color: cyan;}
and not:
body.blue {background-color: cyan;}
Since the color name variables in our actual code have values that are hex values for colors, you might have a variable name like "light-grey" with a value of #eeeeee.
So Sass tries to generate the code and gets something like this:
.##eeeeee { td { background: #eeeeee; etc.
This throws a compilation error because Sass is smart enough to know that #eeeeee is an invalid id.
Unless something has changed recently, Sass doesn't allow for dynamic referencing variables dynamically (i.e., give me the value of the variable whose name is stored in $var-name), so it looks like the Sass map is necessary and the redundancy of variable name and variable value is very specific to this particular application and may be unavoidable.

**Comment by a-fro** [comment]
Thanks to both of you. I guess it's not possible at this time.

**Comment by a-fro** [comment]
@fjp2cornell based on our conversation this morning, I modified the codepen to show how we could make the list a bit cleaner. If you like this approach, I suggest classifying brand colors into light and dark in the variables file, then using the logic here.

**Comment by fjp2cornell** [comment]
Yes, I do like that approach, thanks. I was trying to come up with a similar solution using a second array but did not know how to access the items inside it to perform the check.

**Pull request closed without merging**
